# Generated by Django 5.2 on 2025-04-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
